# Generated by Django 2.2.16 on 2022-09-03 23:02

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220829_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[posts.validators.validate_not_empty], verbose_name='Текст'),
        ),
    ]
